name: Docker Image CI

on:
  push:
    branches: [ "cv-4.7.0" ]
  pull_request:
    branches: [ "cv-4.7.0" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cv-4.7.0:$(date +%s)
